-- =============================================================================
-- seed_data_postgresql.sql — Sample Data for Coffee Shop POS
-- =============================================================================
-- Run this AFTER schema_postgresql.sql to populate the database with test data.
-- This provides realistic sample data for testing all features.
--
-- Includes:
--   - Default admin user (password: admin123)
--   - Sample staff with different roles
--   - Menu categories and items
--   - Restaurant tables
--   - Inventory items
--   - Sample orders for testing reports
-- =============================================================================

-- =============================================================================
-- USERS — password_hash values are BCrypt hashes
-- Default credentials for testing:
--   admin / admin123   (Admin role — full access)
--   manager1 / pass123 (Manager role)
--   cashier1 / pass123 (Cashier role)
--   waiter1 / pass123  (Waiter role)
--
-- These hashes are generated by AuthService.cs using BCrypt.Net
-- =============================================================================
INSERT INTO users (username, password_hash, full_name, role) VALUES
('admin',    '$2a$11$K5Hn8VjKJcMEJq3Rz1X8..ZMd5fY7Sp8e3vKHGQb5p9LjV3Wq0PNm', 'System Admin',    'Admin'),
('manager1', '$2a$11$K5Hn8VjKJcMEJq3Rz1X8..ZMd5fY7Sp8e3vKHGQb5p9LjV3Wq0PNm', 'Sarah Manager',   'Manager'),
('cashier1', '$2a$11$K5Hn8VjKJcMEJq3Rz1X8..ZMd5fY7Sp8e3vKHGQb5p9LjV3Wq0PNm', 'Mike Cashier',    'Cashier'),
('waiter1',  '$2a$11$K5Hn8VjKJcMEJq3Rz1X8..ZMd5fY7Sp8e3vKHGQb5p9LjV3Wq0PNm', 'Emma Waiter',     'Waiter');

-- NOTE: The above hash won't actually validate with BCrypt because it's a placeholder.
-- The application's AuthService will generate proper hashes. For initial setup,
-- use the "Reset Password" feature or update via the app's admin panel.
-- A helper seed script is provided in the README to generate valid hashes.

-- =============================================================================
-- CATEGORIES — Menu groupings used in the POS order screen
-- Connects to: CategoryDAL.cs -> MenuManagementForm.cs, OrderForm.cs
-- =============================================================================
INSERT INTO categories (name, description) VALUES
('Hot Coffee',       'Freshly brewed hot coffee drinks'),
('Cold Coffee',      'Iced and blended coffee beverages'),
('Tea',              'Hot and iced tea selections'),
('Pastries',         'Fresh baked goods and pastries'),
('Sandwiches',       'Light meals and sandwiches'),
('Smoothies',        'Fresh fruit smoothies and shakes'),
('Specialty Drinks', 'Signature and seasonal beverages');

-- =============================================================================
-- MENU ITEMS — Products available for order
-- Connects to: MenuItemDAL.cs -> OrderForm.cs (item selection)
-- Each item references a category_id from the categories table above
-- =============================================================================
INSERT INTO menu_items (category_id, name, description, price) VALUES
-- Hot Coffee (category_id = 1)
(1, 'Espresso',            'Single shot of rich espresso',              2.50),
(1, 'Double Espresso',     'Double shot of espresso',                   3.50),
(1, 'Americano',           'Espresso with hot water',                   3.00),
(1, 'Cappuccino',          'Espresso with steamed milk foam',           4.00),
(1, 'Latte',               'Espresso with steamed milk',                4.50),
(1, 'Mocha',               'Espresso with chocolate and steamed milk',  5.00),
(1, 'Flat White',          'Double espresso with microfoam milk',       4.50),
(1, 'Macchiato',           'Espresso with a dash of milk',              3.50),

-- Cold Coffee (category_id = 2)
(2, 'Iced Americano',      'Cold espresso with ice water',              3.50),
(2, 'Iced Latte',          'Cold espresso with chilled milk',           4.50),
(2, 'Iced Mocha',          'Cold espresso with chocolate and milk',     5.50),
(2, 'Cold Brew',           'Slow-steeped cold coffee',                  4.00),
(2, 'Frappuccino',         'Blended ice coffee with whipped cream',     5.50),

-- Tea (category_id = 3)
(3, 'English Breakfast',   'Classic black tea',                          2.50),
(3, 'Green Tea',           'Japanese green tea',                         2.50),
(3, 'Chamomile',           'Herbal chamomile infusion',                  3.00),
(3, 'Chai Latte',          'Spiced tea with steamed milk',               4.00),
(3, 'Matcha Latte',        'Japanese matcha with steamed milk',          5.00),

-- Pastries (category_id = 4)
(4, 'Croissant',           'Buttery French croissant',                   3.00),
(4, 'Chocolate Muffin',    'Rich chocolate chip muffin',                 3.50),
(4, 'Blueberry Scone',     'Fresh blueberry scone',                      3.50),
(4, 'Cinnamon Roll',       'Warm cinnamon roll with icing',              4.00),
(4, 'Banana Bread',        'Moist banana bread slice',                   3.50),
(4, 'Cookie',              'Large chocolate chip cookie',                 2.50),

-- Sandwiches (category_id = 5)
(5, 'Ham & Cheese Panini', 'Grilled ham and cheese on ciabatta',         6.50),
(5, 'Turkey Club',         'Turkey, bacon, lettuce, tomato',              7.00),
(5, 'Veggie Wrap',         'Fresh vegetables in a whole wheat wrap',     6.00),
(5, 'Egg Breakfast Sandwich', 'Egg, cheese, and bacon on brioche',      5.50),

-- Smoothies (category_id = 6)
(6, 'Berry Blast',         'Mixed berry smoothie',                        5.00),
(6, 'Tropical Paradise',   'Mango, pineapple, coconut blend',            5.50),
(6, 'Green Machine',       'Spinach, banana, apple smoothie',             5.00),

-- Specialty Drinks (category_id = 7)
(7, 'Caramel Macchiato',   'Vanilla, caramel, espresso, steamed milk',   5.50),
(7, 'Vanilla Bean Latte',  'Vanilla bean infused latte',                  5.00),
(7, 'Hazelnut Mocha',      'Hazelnut, chocolate, espresso',              5.50),
(7, 'Pumpkin Spice Latte', 'Seasonal pumpkin spice latte',               5.50);

-- =============================================================================
-- TABLES — Restaurant seating
-- Connects to: TableDAL.cs -> TableManagementForm.cs, OrderForm.cs
-- =============================================================================
INSERT INTO tables (table_number, capacity, status) VALUES
('T1',  2, 'Available'),
('T2',  2, 'Available'),
('T3',  4, 'Available'),
('T4',  4, 'Available'),
('T5',  4, 'Available'),
('T6',  6, 'Available'),
('T7',  6, 'Available'),
('T8',  8, 'Available'),
('T9',  2, 'Available'),
('T10', 4, 'Available');

-- =============================================================================
-- INVENTORY — Raw materials and supplies
-- Connects to: InventoryDAL.cs -> InventoryForm.cs, InventoryService.cs
-- =============================================================================
INSERT INTO inventory (name, unit, quantity, reorder_level, cost_per_unit) VALUES
('Coffee Beans (Arabica)',   'kg',     25.00,  5.00,   15.00),
('Coffee Beans (Robusta)',   'kg',     15.00,  5.00,   12.00),
('Whole Milk',               'liters', 50.00, 10.00,    1.50),
('Oat Milk',                 'liters', 20.00,  5.00,    3.00),
('Sugar',                    'kg',     10.00,  3.00,    2.00),
('Chocolate Syrup',          'liters',  8.00,  2.00,    5.00),
('Vanilla Syrup',            'liters',  6.00,  2.00,    5.50),
('Caramel Syrup',            'liters',  5.00,  2.00,    5.50),
('Whipped Cream',            'liters', 10.00,  3.00,    4.00),
('Tea Bags (Assorted)',      'pcs',   200.00, 50.00,    0.10),
('Matcha Powder',            'kg',      2.00,  0.50,   30.00),
('Croissants (Frozen)',      'pcs',    50.00, 15.00,    1.50),
('Muffin Mix',               'kg',      5.00,  2.00,    4.00),
('Bread (Ciabatta)',         'pcs',    30.00, 10.00,    2.00),
('Ham (Sliced)',             'kg',      3.00,  1.00,   12.00),
('Cheese (Sliced)',          'kg',      3.00,  1.00,   10.00),
('Mixed Berries (Frozen)',   'kg',      5.00,  2.00,    8.00),
('Bananas',                  'pcs',    30.00, 10.00,    0.30),
('Paper Cups (Medium)',      'pcs',   500.00,100.00,    0.05),
('Paper Cups (Large)',       'pcs',   400.00,100.00,    0.07),
('Napkins',                  'pcs',  1000.00,200.00,    0.02);
